#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure net/bind910

  block compile gitsubmodule

  cd "$shome/vendor/getssl"
  git reset --hard "v$GETSSL_VERSION"

  cd "$shome/vendor/checkssl"
  git reset --hard "v$CHECKSSL_VERSION"
}

main "$@"
