#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin)
      true
      ;;
    *)
      pkg ensure bind net/bind910
      ;;
  esac

  git clone -b "v${GETSSL_VERSION}" git@github.com:srvrco/getssl "$shome/vendor/getssl-${GETSSL_VERSION}" || true
  rm -rf "$shome/vendor/getssl"
  ln -nfs "getssl-${GETSSL_VERSION}" "$shome/vendor/getssl"

  git clone -b "v${CHECKSSL_VERSION}" git@github.com:srvrco/checkssl "$shome/vendor/checkssl-${CHECKSSL_VERSION}" || true
  rm -rf "$shome/vendor/checkssl"
  ln -nfs "checkssl-${CHECKSSL_VERSION}" "$shome/vendor/checkssl"
}

main "$@"
