#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_getssl="$(env USE_DEBUG=1 getssl 2>/dev/null | head -1 | awk '{print $3}' || true)"
  jq -n --arg getssl "$ver_getssl" '{getssl: $getssl}'
}

version "$@"
